# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
